# Generated by Django 2.2.1 on 2019-06-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.AutoField(auto_created=100001, primary_key=True, serialize=False)),
                ('type_id', models.CharField(choices=[(0, '手机'), (1, '农用物资'), (2, '生鲜水果'), (3, '园艺植物'), (4, '五金工具'), (5, '电子零件'), (6, '动漫/周边'), (7, '宠物用品'), (8, '网络设备'), (9, '服饰/配饰'), (10, '家装建材'), (11, '家纺布艺'), (12, '珠宝首饰'), (13, '游戏'), (14, '办公用品'), (15, '图书'), (16, '运动户外'), (17, '票务娱乐'), (18, '玩具'), (19, '车辆'), (20, '其他')], max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('number', models.IntegerField()),
                ('desc', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(auto_created=10000000, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Buyer', to_field='buyer_id')),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_app.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Buyer', to_field='buyer_id')),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_app.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Buyer', to_field='buyer_id')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_app.Order')),
            ],
        ),
    ]
